### ISSUE TITLE
Extension hangs without eio_init(), PHP 8 completely broken

### ISSUE THREAD

**Issue by enumag** [rosmanov/pecl-eio#13]
After upgrading to PHP 8 and ext-eio 3.0.0RC2, I encountered an issue where the script hanged. Since it was very odd and I couldn't be sure if it's Amphp's problem or Eio's problem, I left it be until I had more time to figure it out. Now I finally managed to get to it.

After analysis the same thing actually happens on PHP 7.4 as well with both ext-eio 2.0 and ext-eio 3.0.0RC2. However it can be fixed by manually calling the `eio_init()` function (which Amphp now once again does on it's own after https://github.com/amphp/file/pull/61).

**On the PHP 8's version of the extension this function no longer exists and therefore the bug is impossible to fix in userland code.**

To reproduce the problem create a directory and inside it a `Dockerfile` with this content:

```
ARG PHP_VERSION=8.0

FROM php:${PHP_VERSION}

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

WORKDIR /usr/app

RUN apt-get update && \
    apt-get install -qq git unzip ${PHPIZE_DEPS} && \
    pecl install eio-beta && \
    docker-php-ext-enable eio && \
    git clone https://github.com/amphp/file.git . && \
    composer install --ignore-platform-reqs

RUN echo '<?php\n\
use Amp\File\Driver\EioDriver;\n\
use Amp\Loop;\n\
require __DIR__ . "/vendor/autoload.php";\n\
echo phpversion() . PHP_EOL;\n\
echo phpversion("eio") . PHP_EOL;\n\
Loop::run(\n\
    function (): Generator {\n\
        $driver = new EioDriver(Loop::get());\n\
        $list = yield $driver->listFiles(__DIR__);\n\
        echo count($list);\n\
    }\n\
);\n\
' >> ./test.php
```

Then run:

```
docker build . --tag eio-bug
docker run -it eio-bug sh -c "php test.php"
```

The script will hang but will resume if you press enter.

Running it like this instead also fixes it:

```
docker run -it eio-bug sh -c "echo '\n' | php test.php"
```

The exact same issue can be reproduced on PHP 7 after hacking amphp/file to not call the `eio_init()` regardless of ext-eio version.

According to the [source code](https://github.com/rosmanov/pecl-eio/blob/ca8ee594118f7cef28a457771f0387a59c082c78/php7/php_eio.c#L1160-L1170) you attempted to make `eio_init()` calls unnecessary and didn't port it to the PHP 8 version. Sadly as my reproducer shows, calling it silently doesn't work well enough at the moment.

**Comment by rosmanov** [comment]
Try using this [Dockerfile.txt](https://github.com/rosmanov/pecl-eio/files/7196560/Dockerfile.txt):
```
$ docker build -f Dockerfile.txt -t eio-hangs .
# ...
$ docker run eio-hangs
+++ dirname ./pecl-eio-issue-13/run.sh
++ cd ./pecl-eio-issue-13
++ pwd
+ dir=/usr/app/pecl-eio-issue-13
++ php-config --extension-dir
+ sockets_so_path=/usr/local/lib/php/extensions/no-debug-non-zts-20200930/sockets.so
+ sockets_option=
+ '[' -e /usr/local/lib/php/extensions/no-debug-non-zts-20200930/sockets.so ']'
+ MALLOC_PERTURB_=59
+ MALLOC_CHECK_=3
+ USE_ZEND_ALLOC=0
+ ZEND_DONT_UNLOAD_MODULES=1
+ php -n -d extension=eio.so -dextension_dir=/usr/app/pecl-eio-issue-13/.libs test.php
8.0.10
3.0.0RC2
16
```

I've put the `eio_init()` into MINIT. For some reason, I wanted to avoid doing this initially, but now I think it won't hurt at all. What do you think?

**Comment by enumag** [comment]
Yup, I can confirm that this works. I only noticed some warnings during compilation but it didn't fail and I my script doesn't hang anymore.

Here are the warnings in case you wanna fix them.

```
In file included from /usr/app/pecl-eio-master/php8/php_eio.c:72:
./libeio/eio.c: In function 'eio__mtouch':
./libeio/eio.c:1324:8: warning: suggest explicit braces to avoid ambiguous 'else' [-Wdangling-else]
 1324 |     if (addr < end)
      |        ^
./libeio/eio.c: In function 'eio__scandir':
./libeio/eio.c:1806:19: warning: suggest explicit braces to avoid ambiguous 'else' [-Wdangling-else]
 1806 |           else if (flags & EIO_READDIR_DIRS_FIRST)
      |                   ^
In file included from /usr/app/pecl-eio-master/php8/php_eio.c:72:
./libeio/eio.c: In function 'etp_proc':
./libeio/eio.c:2197:1: warning: no return statement in function returning non-void [-Wreturn-type]
 2197 | }
      | ^
```

**Comment by rosmanov** [comment]
@enumag , Thank you.

Okay, then I'll review the changes, merge them and publish a new PECL package soon. If nobody has objections against putting `eio_init()` into the MINIT phase.

**Comment by enumag** [comment]
Can't say I know what the MINIT phase is so I can hardly complain about it. :-D Good job! Thanks for fast solution!

**Comment by rosmanov** [comment]
Version 3.0.0RC3 (beta) has been release. Please check it out.

**Comment by enumag** [comment]
Thanks a lot @rosmanov!
