### ISSUE TITLE
About pecl-eio unable to use. Please help me

### ISSUE THREAD

**Issue by 1242048704** [rosmanov/pecl-eio#17]
Thank you for your open source contributions Sincerely! When I m in my server(php version 8.1) install pecl-eio, I found that it couldn't run eio functions correctly and `php -m`  display `eio` extension. Mistakes like  `Fatal error: Uncaught Error: Call to undefined function eio_open()` and so on.  I look forward to hearing from you!

```php
$str      = str_repeat('1', 20);
$filename = '/tmp/tmp_file' .uniqid();
@unlink($filename);
touch($filename);
eio_open($filename, EIO_O_RDWR, 0, EIO_PRI_DEFAULT, function($filename, $fd) use ($str) {
    eio_write($fd, $str, strlen($str), 0, 0, function($fd, $written) use ($str, $filename) {
        var_dump([
            'written'  => $written,
            'strlen'   => strlen($str),
            'filesize' => filesize($filename),
            'count'    => substr_count(file_get_contents($filename), '1')
        ]);
    }, $fd);
}, $filename);
eio_event_loop();
```

**Comment by 1242048704** [comment]
and my PHP run in PHP-FPM

**Comment by rosmanov** [comment]
Hello,

> Thank you for your open source contributions Sincerely!

I'm glad you find it useful, thanks.

> php -m display eio extension
> ... and my PHP run in PHP-FPM

eio extension is designed to work in CLI and its behavior in other SAPIs is undefined, sorry. The fact that  `php -m` shows "eio" means that the extension is only enabled for the CLI sapi. FPM is a different SAPI with its own configuration (you can see the loaded .ini files and directories it scans for .ini files using `phpinfo()` function call.)

By the way, if you are using "sockets" extension, please make sure to load `sockets.so` *before* `eio.so`. This can be done by prefixing the sockets' .ini file with a less than the prefix for eio, in lexicographic order e.g.

```
/etc/php.d/20-sockets.ini
/etc/php.d/99-eio.ini
```

The ini directory can be found in the output produced by the `phpinfo()`  function call, for instance (can be useful in FPM). In CLI, it can be found in the output of `php -i` or `php-config --ini-dir`.

Good luck.

**Comment by 1242048704** [comment]
> Hello,
> 
> > Thank you for your open source contributions Sincerely!
> 
> I'm glad you find it useful, thanks.
> 
> > php -m display eio extension
> > ... and my PHP run in PHP-FPM
> 
> eio extension is designed to work in CLI and its behavior in other SAPIs is undefined, sorry. The fact that `php -m` shows "eio" means that the extension is only enabled for the CLI sapi. FPM is a different SAPI with its own configuration (you can see the loaded .ini files and directories it scans for .ini files using `phpinfo()` function call.)
> 
> By the way, if you are using "sockets" extension, please make sure to load `sockets.so` _before_ `eio.so`. This can be done by prefixing the sockets' .ini file with a character sequence less than that of the eio .ini filename, in lexicographic order e.g.
> 
> ```
> /etc/php.d/20-sockets.ini
> /etc/php.d/99-eio.ini
> ```
> 
> The ini directory can be found in the output produced by the `phpinfo()` function call, for instance (can be useful in FPM). In CLI, it can be found in the output of `php -i` or `php-config --ini-dir`.
> 
> Good luck

Grateful！I get it ！Ура! товарищ！
