### ISSUE TITLE
Please release 3.1.0

### ISSUE THREAD

**Issue by remicollet** [rosmanov/pecl-eio#20]
Only about version number.

As **3.1.0RC1** was released on pecl, it is not possible to simply update to the latest stable **3.0.1**

**Comment by rosmanov** [comment]
Yes, that was a typo. Actually, I meant to create version 3.1.0 instead of 3.0.1, sorry.

The new version 3.1.0 has been uploaded.

Thanks.

**Comment by remicollet** [comment]
Thanks for the quick fix
